# Generated by Django 6.0.1 on 2026-02-03 22:39

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django_advance_thumbnail.fields
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True)),
                ('citation_name', models.CharField(blank=True, db_index=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_1821cf_gin')],
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_96a5dc_gin')],
            },
        ),
        migrations.CreateModel(
            name='InscriptionStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'digital_mary_inscription_style',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_79859f_gin')],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('inscription', models.TextField(blank=True, null=True)),
                ('translated_inscription', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('dimensions', models.TextField(blank=True, null=True)),
                ('bibliographic_references', models.TextField(blank=True, null=True)),
                ('display_date', models.CharField(blank=True, null=True)),
                ('earliest_creation', models.IntegerField(blank=True, choices=[(None, 'Unknown'), (1, '1st Century'), (2, '2nd Century'), (3, '3rd Century'), (4, '4th Century'), (5, '5th Century'), (6, '6th Century'), (7, '7th Century'), (8, '8th Century'), (9, '9th Century'), (10, '10th Century'), (11, '11th Century'), (12, '12th Century'), (13, '13th Century'), (14, '14th Century'), (15, '15th Century'), (16, '16th Century'), (17, '17th Century'), (18, '18th Century'), (19, '19th Century'), (20, '20th Century'), (21, '21st Century')], null=True)),
                ('latest_creation', models.IntegerField(blank=True, choices=[(None, 'Unknown'), (1, '1st Century'), (2, '2nd Century'), (3, '3rd Century'), (4, '4th Century'), (5, '5th Century'), (6, '6th Century'), (7, '7th Century'), (8, '8th Century'), (9, '9th Century'), (10, '10th Century'), (11, '11th Century'), (12, '12th Century'), (13, '13th Century'), (14, '14th Century'), (15, '15th Century'), (16, '16th Century'), (17, '17th Century'), (18, '18th Century'), (19, '19th Century'), (20, '20th Century'), (21, '21st Century')], null=True)),
                ('culture_other', models.TextField(blank=True, null=True, verbose_name='culture (unknown)')),
                ('findspot_other', models.TextField(blank=True, null=True, verbose_name='findspot (unknown)')),
                ('provenance_other', models.TextField(blank=True, null=True, verbose_name='provenance (unknown)')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name', 'description', 'translated_inscription', 'location', 'dimensions', 'bibliographic_references', 'culture_other', 'findspot_other', 'provenance_other'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='items', to='digital_mary.category')),
                ('cultures', models.ManyToManyField(blank=True, related_name='items', to='digital_mary.culture')),
                ('inscription_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digital_mary.inscriptionstyle')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Image Name')),
                ('is_public', models.BooleanField(db_index=True, default=False, verbose_name='Is Public?')),
                ('image', models.ImageField(height_field='image_height', help_text='Please use <u><a href="https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types" target="_blank">standard web image types</a></u>. PNG, JPEG, and WebP are recommended.', upload_to='images/', width_field='image_width')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('thumbnail', django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to='thumbnails/')),
                ('description', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='digital_mary.item')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_d031e4_gin')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='items', to='digital_mary.language'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alternate_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list)),
                ('geonameid', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_4d42ac_gin')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='findspot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fondspot_items', to='digital_mary.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenace_items', to='digital_mary.location'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_6dba87_gin')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='items', to='digital_mary.material'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marc_relators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('abr', 'Abridger'), ('act', 'Actor'), ('adp', 'Adapter'), ('rcp', 'Addressee'), ('anl', 'Analyst'), ('anm', 'Animator'), ('ann', 'Annotator'), ('anc', 'Announcer'), ('apl', 'Appellant'), ('ape', 'Appellee'), ('app', 'Applicant'), ('arc', 'Architect'), ('arr', 'Arranger'), ('acp', 'Art copyist'), ('adi', 'Art director'), ('art', 'Artist'), ('ard', 'Artistic director'), ('asg', 'Assignee'), ('asn', 'Associated name'), ('att', 'Attributed name'), ('auc', 'Auctioneer'), ('aue', 'Audio engineer'), ('aup', 'Audio producer'), ('aut', 'Author'), ('aqt', 'Author in quotations or text abstracts'), ('aft', 'Author of afterword, colophon, etc.'), ('aud', 'Author of dialog'), ('aui', 'Author of introduction, etc.'), ('ato', 'Autographer'), ('ant', 'Bibliographic antecedent'), ('bnd', 'Binder'), ('bdd', 'Binding designer'), ('blw', 'Blurb writer'), ('bka', 'Book artist'), ('bkd', 'Book designer'), ('bkp', 'Book producer'), ('bjd', 'Bookjacket designer'), ('bpd', 'Bookplate designer'), ('bsl', 'Bookseller'), ('brl', 'Braille embosser'), ('brd', 'Broadcaster'), ('cll', 'Calligrapher'), ('cop', 'Camera operator'), ('ctg', 'Cartographer'), ('cas', 'Caster'), ('cad', 'Casting director'), ('cns', 'Censor'), ('chr', 'Choreographer'), ('cng', 'Cinematographer'), ('cli', 'Client'), ('cor', 'Collection registrar'), ('col', 'Collector'), ('clt', 'Collotyper'), ('clr', 'Colorist'), ('cmm', 'Commentator'), ('cwt', 'Commentator for written text'), ('com', 'Compiler'), ('cpl', 'Complainant'), ('cpt', 'Complainant-appellant'), ('cpe', 'Complainant-appellee'), ('cmp', 'Composer'), ('cmt', 'Compositor'), ('ccp', 'Conceptor'), ('cnd', 'Conductor'), ('con', 'Conservator'), ('csl', 'Consultant'), ('csp', 'Consultant to a project'), ('cos', 'Contestant'), ('cot', 'Contestant-appellant'), ('coe', 'Contestant-appellee'), ('cts', 'Contestee'), ('ctt', 'Contestee-appellant'), ('cte', 'Contestee-appellee'), ('ctr', 'Contractor'), ('ctb', 'Contributor'), ('cpc', 'Copyright claimant'), ('cph', 'Copyright holder'), ('crr', 'Corrector'), ('crp', 'Correspondent'), ('cst', 'Costume designer'), ('cou', 'Court governed'), ('crt', 'Court reporter'), ('cov', 'Cover designer'), ('cre', 'Creator'), ('cur', 'Curator'), ('dnc', 'Dancer'), ('dtc', 'Data contributor'), ('dtm', 'Data manager'), ('dte', 'Dedicatee'), ('dto', 'Dedicator'), ('dfd', 'Defendant'), ('dft', 'Defendant-appellant'), ('dfe', 'Defendant-appellee'), ('dgc', 'Degree committee member'), ('dgg', 'Degree granting institution'), ('dgs', 'Degree supervisor'), ('dln', 'Delineator'), ('dpc', 'Depicted'), ('dpt', 'Depositor'), ('dsr', 'Designer'), ('drt', 'Director'), ('dis', 'Dissertant'), ('dbp', 'Distribution place'), ('djo', 'DJ'), ('dnr', 'Donor'), ('drm', 'Draftsman'), ('dbd', 'Dubbing director'), ('dub', 'Dubious author'), ('edt', 'Editor'), ('edc', 'Editor of compilation'), ('edm', 'Editor of moving image work'), ('edd', 'Editorial director'), ('elg', 'Electrician'), ('elt', 'Electrotyper'), ('enj', 'Enacting jurisdiction'), ('eng', 'Engineer'), ('egr', 'Engraver'), ('etr', 'Etcher'), ('evp', 'Event place'), ('exp', 'Expert'), ('fac', 'Facsimilist'), ('fld', 'Field director'), ('fmd', 'Film director'), ('fds', 'Film distributor'), ('flm', 'Film editor'), ('fmp', 'Film producer'), ('fmk', 'Filmmaker'), ('fpy', 'First party'), ('frg', 'Forger'), ('fmo', 'Former owner'), ('fon', 'Founder'), ('fnd', 'Funder'), ('gis', 'Geographic information specialist'), ('hnr', 'Honoree'), ('hst', 'Host'), ('his', 'Host institution'), ('ilu', 'Illuminator'), ('ill', 'Illustrator'), ('ins', 'Inscriber'), ('itr', 'Instrumentalist'), ('ive', 'Interviewee'), ('ivr', 'Interviewer'), ('inv', 'Inventor'), ('isb', 'Issuing body'), ('jud', 'Judge'), ('jug', 'Jurisdiction governed'), ('lbr', 'Laboratory'), ('ldr', 'Laboratory director'), ('lsa', 'Landscape architect'), ('led', 'Lead'), ('len', 'Lender'), ('lil', 'Libelant'), ('lit', 'Libelant-appellant'), ('lie', 'Libelant-appellee'), ('lel', 'Libelee'), ('let', 'Libelee-appellant'), ('lee', 'Libelee-appellee'), ('lbt', 'Librettist'), ('lse', 'Licensee'), ('lso', 'Licensor'), ('lgd', 'Lighting designer'), ('ltg', 'Lithographer'), ('lyr', 'Lyricist'), ('mka', 'Makeup artist'), ('mfp', 'Manufacture place'), ('mfr', 'Manufacturer'), ('mrb', 'Marbler'), ('mrk', 'Markup editor'), ('med', 'Medium'), ('mdc', 'Metadata contact'), ('mte', 'Metal-engraver'), ('mtk', 'Minute taker'), ('mxe', 'Mixing engineer'), ('mod', 'Moderator'), ('mon', 'Monitor'), ('mcp', 'Music copyist'), ('mup', 'Music programmer'), ('msd', 'Musical director'), ('mus', 'Musician'), ('nrt', 'Narrator'), ('nan', 'News anchor'), ('onp', 'Onscreen participant'), ('osp', 'Onscreen presenter'), ('opn', 'Opponent'), ('orm', 'Organizer'), ('org', 'Originator'), ('oth', 'Other'), ('own', 'Owner'), ('pan', 'Panelist'), ('ppm', 'Papermaker'), ('pta', 'Patent applicant'), ('pth', 'Patent holder'), ('pat', 'Patron'), ('prf', 'Performer'), ('pma', 'Permitting agency'), ('pht', 'Photographer'), ('pad', 'Place of address'), ('ptf', 'Plaintiff'), ('ptt', 'Plaintiff-appellant'), ('pte', 'Plaintiff-appellee'), ('plt', 'Platemaker'), ('pra', 'Praeses'), ('pre', 'Presenter'), ('prt', 'Printer'), ('pop', 'Printer of plates'), ('prm', 'Printmaker'), ('prc', 'Process contact'), ('pro', 'Producer'), ('prn', 'Production company'), ('prs', 'Production designer'), ('pmn', 'Production manager'), ('prd', 'Production personnel'), ('prp', 'Production place'), ('prg', 'Programmer'), ('pdr', 'Project director'), ('pfr', 'Proofreader'), ('prv', 'Provider'), ('pup', 'Publication place'), ('pbl', 'Publisher'), ('pbd', 'Publishing director'), ('ppt', 'Puppeteer'), ('rdd', 'Radio director'), ('rpc', 'Radio producer'), ('rap', 'Rapporteur'), ('rce', 'Recording engineer'), ('rcd', 'Recordist'), ('red', 'Redaktor'), ('rxa', 'Remix artist'), ('ren', 'Renderer'), ('rpt', 'Reporter'), ('rps', 'Repository'), ('rth', 'Research team head'), ('rtm', 'Research team member'), ('res', 'Researcher'), ('rsp', 'Respondent'), ('rst', 'Respondent-appellant'), ('rse', 'Respondent-appellee'), ('rpy', 'Responsible party'), ('rsg', 'Restager'), ('rsr', 'Restorationist'), ('rev', 'Reviewer'), ('rbr', 'Rubricator'), ('sce', 'Scenarist'), ('sad', 'Scientific advisor'), ('aus', 'Screenwriter'), ('scr', 'Scribe'), ('scl', 'Sculptor'), ('spy', 'Second party'), ('sec', 'Secretary'), ('sll', 'Seller'), ('std', 'Set designer'), ('stg', 'Setting'), ('sgn', 'Signer'), ('sng', 'Singer'), ('swd', 'Software developer'), ('sds', 'Sound designer'), ('sde', 'Sound engineer'), ('spk', 'Speaker'), ('sfx', 'Special effects provider'), ('spn', 'Sponsor'), ('sgd', 'Stage director'), ('stm', 'Stage manager'), ('stn', 'Standards body'), ('str', 'Stereotyper'), ('stl', 'Storyteller'), ('sht', 'Supporting host'), ('srv', 'Surveyor'), ('tch', 'Teacher'), ('tcd', 'Technical director'), ('tld', 'Television director'), ('tlg', 'Television guest'), ('tlh', 'Television host'), ('tlp', 'Television producer'), ('tau', 'Television writer'), ('ths', 'Thesis advisor'), ('trc', 'Transcriber'), ('trl', 'Translator'), ('tyd', 'Type designer'), ('tyg', 'Typographer'), ('uvp', 'University place'), ('vdg', 'Videographer'), ('vfx', 'Visual effects provider'), ('vac', 'Voice actor'), ('wit', 'Witness'), ('wde', 'Wood engraver'), ('wdc', 'Woodcutter'), ('wam', 'Writer of accompanying material'), ('wac', 'Writer of added commentary'), ('wal', 'Writer of added lyrics'), ('wat', 'Writer of added text'), ('win', 'Writer of introduction'), ('wpr', 'Writer of preface'), ('wst', 'Writer of supplementary textual content')]), default=list, verbose_name='roles')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='digital_mary.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='digital_mary.person')),
            ],
            options={'ordering': ['person__citation_name']},
        ),
        migrations.CreateModel(
            name='RemoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Image Name')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_images', to='digital_mary.item')),
            ],
            options={
                'db_table': 'digital_mary_remote_image',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alternate_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=list)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_fe0f65_gin')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='items', to='digital_mary.subject'),
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('label', 'description'), required_languages=(), virtual_fields=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_74282b_gin')],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='techniques',
            field=models.ManyToManyField(blank=True, related_name='items', to='digital_mary.technique'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['i18n'], name='digital_mar_i18n_91c5c5_gin'),
        ),
    ]
