# Generated by Django 6.0.1 on 2026-02-06 21:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_mary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='interpretations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('i18n__name_ar', config='arabic', weight='A'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('description', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('i18n__description_ar', config='arabic', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('translated_inscription', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('i18n__translated_inscription_ar', config='arabic', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('inscription', config='simple', weight='C'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AlterField(
            model_name='item',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description', 'translated_inscription', 'location', 'dimensions', 'interpretations', 'bibliographic_references', 'culture_other', 'findspot_other', 'provenance_other'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddIndex(
            model_name='item',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='digital_mar_search__247810_gin'),
        ),
    ]
