# Generated by Django 6.0.1 on 2026-02-12 22:36

import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_mary', '0002_item_interpretations_item_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description', 'license'), required_languages=(), virtual_fields=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is Public?'),
        ),
        migrations.AddField(
            model_name='remoteimage',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
