# Generated by Django 6.0.1 on 2026-03-06 21:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_mary', '0003_image_i18n_item_is_public_remoteimage_i18n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='geonameid',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='geom_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Geo Point'),
        ),
    ]
