# Generated by Django 6.0.1 on 2026-03-06 22:36

import django.db.models.deletion
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_mary', '0004_remove_location_geonameid_remove_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='provenance',
            new_name='provenience',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='provenance_other',
            new_name='provenience_other',
        ),
        migrations.AlterField(
            model_name='item',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description', 'translated_inscription', 'location', 'dimensions', 'interpretations', 'bibliographic_references', 'culture_other', 'findspot_other', 'provenience_other'), required_languages=(), virtual_fields=True),
        ),
    ]
