# Generated by Django 6.0.1 on 2026-03-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_mary', '0005_remove_item_provenance_remove_item_provenance_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='provenience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='provenience_other',
            field=models.TextField(blank=True, null=True, verbose_name='provenience (unknown)'),
        ),
    ]
