# Generated by Django 6.0.1 on 2026-03-06 22:55

import django.db.models.deletion
import modeltrans.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_mary', '0006_alter_item_provenience_alter_item_provenience_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenace_items', to='digital_mary.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='provenance_other',
            field=models.TextField(blank=True, null=True, verbose_name='provenance (unknown)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'description', 'translated_inscription', 'location', 'dimensions', 'interpretations', 'bibliographic_references', 'culture_other', 'findspot_other', 'provenance_other', 'provenience_other'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='provenience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provenience_items', to='digital_mary.location'),
        ),
    ]
