# Generated by Django 6.0.1 on 2026-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_mary', '0007_item_provenance_item_provenance_other_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='remoteimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='remoteimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
