# Generated by Django 6.0.1 on 2026-02-04 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digital_mary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField()),
                ('email', models.EmailField()),
                ('message', models.TextField()),
                ('archive', models.BooleanField(default=False, verbose_name='archived?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='digital_mary.item')),
            ],
        ),
    ]
